server.port=8080
spring.application.name=todolist
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true




#spring.application.name=todolist

## The JDBC URL for connecting to the H2 in-memory database
## "mem" indicates an in-memory database, and "todolist" is the database name
#spring.datasource.url=jdbc:h2:mem:todolist

## The H2 database does not require a username and password, but you can specify them if needed
#spring.datasource.username=sa
#spring.datasource.password=

## The Hibernate dialect for H2, which specifies how Hibernate should generate SQL queries for the H2 database
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

## Hibernate setting that automatically creates and drops the database schema on application startup and shutdown
## This is useful for testing since the database will reset each time the application starts
#spring.jpa.hibernate.ddl-auto=create-drop

## The port where the Spring Boot application will run (default is 8080, but here it's changed to 8082)
#server.port=8082

## Enabling H2 console for web access, typically available at http://localhost:8082/h2-console
#spring.h2.console.enabled=true
